export enum MissionType {
	HADIR_BERTURUT_TURUT = 1,
	SELESAIKAN_QUIZ = 2,
	BERTANYA_DISKUSI = 3,
	MENGIRIM_PESAN_GANESH_BOT = 4
}

export enum LencanaType {
	HADIR_BERTURUT_TURUT = 1,
	MENYELESAIKAN_STAGE = 2,
	MENJAWAB_DISKUSI = 4,
	MENGIRIM_PESAN_GANESH_BOT = 5,
}
